import "./globals.css";
import MockServiceWorkerProvider from "@/providers/mock-service-worker-provider";
import ReactQueryProvider from "@/providers/react-query-provider";

export const metadata = {
  title: "News Application",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <MockServiceWorkerProvider> */}
      <ReactQueryProvider>
        <body>{children}</body>
      </ReactQueryProvider>
      {/* </MockServiceWorkerProvider> */}
    </html>
  );
}
